### ISSUE TITLE
Kotlin Gradle plugin version not satisfy

### ISSUE THREAD

**Issue by Doflatango** [yasukotelin/ext_storage#1]
>The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':ext_storage' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

I'm using **Android Studio 3.5** and **gradle 3.5.1**.

Change the `ext.kotlin_version` to 1.3.10 and fixed the problem.

**Comment by yasukotelin** [comment]
@Doflatango 
Thanks for your Issue!!

> Change the ext.kotlin_version to 1.3.10 and fixed the problem.

It's great. I changed the kotlin version to it and publish fixed it.
Check the ext_storage updated version 1.0.2😍
