### ISSUE TITLE
ext_storage not run in IOS

### ISSUE THREAD

**Issue by DamianRincon** [yasukotelin/ext_storage#14]
- `ext_storage` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
- :c
![Captura de Pantalla 2021-04-14 a la(s) 10 20 01](https://user-images.githubusercontent.com/31808361/114735611-faecf880-9d0a-11eb-96e7-89e522225e0b.png)

**Comment by Aitor1111** [comment]
Same here, did you solve it?

**Comment by mvarendorff** [comment]
The README explicitly states this plugin only supports Android under Features.

**Comment by renolation** [comment]
they said it only works on ANDROID.

**Comment by paakjis** [comment]
![Screen Shot 2021-12-29 at 14 56 07](https://user-images.githubusercontent.com/1484602/147664533-6201c7be-0042-437a-9820-106ed2538ca7.png)

You should iOS from there.
