### ISSUE TITLE
Downloads directory is wrong

### ISSUE THREAD

**Issue by nioncode** [yasukotelin/ext_storage#3]
Thanks for the plugin!

However, the string value for `DIRECTORY_DOWNLOADS` is wrong, it should be `Download` (without the s). This makes files created in this directory not show up in the default download folder.

**Comment by yasukotelin** [comment]
@nioncode 
It's true! Thank you😍
I'll fix it right up💪

**Comment by yasukotelin** [comment]
@nioncode 
I fixed it. Please update and check it🕺🏻
https://pub.dev/packages/ext_storage

**Comment by nioncode** [comment]
Thanks for the fast update, works like a charm now :+1:
