### ISSUE TITLE
iOS

### ISSUE THREAD

**Issue by PhyoeKo** [yasukotelin/ext_storage#5]
How about directory for iOS.

**Comment by yasukotelin** [comment]
@PhyoeKo Sorry, this library uses Android Native API and only support Android. I don't know iOS😇

**Comment by deandreamatias** [comment]
Maybe you can close this issue

**Comment by vipulg114** [comment]
if it doesnot support iOS why does it say iOS supported on pub.dev

![image](https://user-images.githubusercontent.com/30376051/91544255-17cfe980-e93d-11ea-982f-75ade0a98cac.png)

**Comment by gagandeep-s** [comment]
@deandreamatias I can work on this to make it working on iOS as well.

**Comment by dreyrz** [comment]
still doesnt work on ios.
